server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/atm_contratos_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=richar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
app.jwt.secret=BN_ATM_CONTRATOS_SECRET_KEY_2026_MIN_32_CHARS
app.jwt.expiration-ms=86400000

# Carpeta local de tu computadora donde se guardarán documentos, actas DOCX/PDF y firmadas.
# En Windows se recomienda dejarlo así o cambiarlo por otra ruta, por ejemplo D:/BN_ATM_CONTRATOS
app.storage-dir=C:/BN_ATM_CONTRATOS
app.upload-dir=${app.storage-dir}/uploads
app.actas-dir=${app.storage-dir}/actas

springdoc.swagger-ui.path=/swagger-ui/index.html
