package com.bn.atmcontratos.util;
import org.apache.poi.ss.usermodel.*; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.math.BigDecimal; import java.nio.charset.StandardCharsets; import java.text.Normalizer; import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*;
public class ExcelUtil{
 public static List<Map<String,String>> read(MultipartFile f)throws Exception{String n=Optional.ofNullable(f.getOriginalFilename()).orElse("").toLowerCase(); return n.endsWith(".csv")||n.endsWith(".txt")?csv(f):xlsx(f);}
 static List<Map<String,String>> csv(MultipartFile f)throws Exception{List<Map<String,String>> rows=new ArrayList<>(); try(BufferedReader br=new BufferedReader(new InputStreamReader(f.getInputStream(),StandardCharsets.UTF_8))){String h=br.readLine(); if(h==null)return rows; String sep=h.contains(";")?";":","; List<String> headers=Arrays.stream(h.split(sep,-1)).map(ExcelUtil::norm).toList(); String line; while((line=br.readLine())!=null){String[] p=line.split(sep,-1); Map<String,String> m=new HashMap<>(); for(int i=0;i<headers.size()&&i<p.length;i++)m.put(headers.get(i),p[i].trim()); rows.add(m);}} return rows;}
 static List<Map<String,String>> xlsx(MultipartFile f)throws Exception{List<Map<String,String>> rows=new ArrayList<>(); try(Workbook wb=WorkbookFactory.create(f.getInputStream())){Sheet sh=wb.getSheetAt(0); Iterator<Row> it=sh.iterator(); if(!it.hasNext())return rows; DataFormatter fmt=new DataFormatter(); List<String> h=new ArrayList<>(); for(Cell c:it.next())h.add(norm(fmt.formatCellValue(c))); while(it.hasNext()){Row r=it.next(); Map<String,String> m=new HashMap<>(); boolean ok=false; for(int i=0;i<h.size();i++){String v=fmt.formatCellValue(r.getCell(i,Row.MissingCellPolicy.RETURN_BLANK_AS_NULL)).trim(); if(!v.isBlank())ok=true; m.put(h.get(i),v);} if(ok)rows.add(m);}} return rows;}
 public static String get(Map<String,String> r,String...names){for(String n:names){String v=r.get(norm(n)); if(v!=null&&!v.isBlank())return v.trim();} return null;}
 public static String norm(String s){if(s==null)return ""; return Normalizer.normalize(s,Normalizer.Form.NFD).replaceAll("\\p{M}","").replaceAll("[^A-Za-z0-9]","").toLowerCase();}
 public static BigDecimal money(String s){if(s==null||s.isBlank())return BigDecimal.ZERO; try{return new BigDecimal(s.replace("S/","").replace("US$","").replace("$","").replace(",","").trim());}catch(Exception e){return BigDecimal.ZERO;}}
 public static LocalDate date(String s){if(s==null||s.isBlank())return null; for(String p:List.of("M/d/yyyy","MM/dd/yyyy","d/M/yyyy","dd/MM/yyyy","yyyy-MM-dd"))try{return LocalDate.parse(s.trim(),DateTimeFormatter.ofPattern(p));}catch(Exception ignored){} return null;}
}
