package com.bn.atmcontratos.service;
import com.bn.atmcontratos.dto.*; import com.bn.atmcontratos.model.entity.*; import com.bn.atmcontratos.model.enums.*; import com.bn.atmcontratos.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import java.math.*; import java.time.*; import java.util.*; import java.util.stream.*;
@Service @RequiredArgsConstructor public class DashboardService{
 private final AtmRepository atms; private final ProveedorRepository proveedores; private final ContratoRepository contratos; private final ActaConformidadRepository actas;
 public DashboardResumen resumen(){List<Contrato> cs=contratos.findAll(); cs.forEach(Contrato::recalcular); int m=LocalDate.now().getMonthValue(), y=LocalDate.now().getYear(); var am=actas.findByMesAndAnio(m,y); BigDecimal mensual=cs.stream().map(c->c.getMontoTotalMensual()==null?BigDecimal.ZERO:c.getMontoTotalMensual()).reduce(BigDecimal.ZERO,BigDecimal::add); BigDecimal total=cs.stream().map(c->c.getMontoContrato()==null?BigDecimal.ZERO:c.getMontoContrato()).reduce(BigDecimal.ZERO,BigDecimal::add); return new DashboardResumen(atms.count(),proveedores.count(),cs.size(),cnt(cs,EstadoContrato.VIGENTE),cnt(cs,EstadoContrato.POR_VENCER_30),cnt(cs,EstadoContrato.POR_VENCER_60),cnt(cs,EstadoContrato.POR_VENCER_90),cnt(cs,EstadoContrato.VENCIDO),am.stream().filter(a->a.getEstado()==EstadoActa.PENDIENTE).count(),am.stream().filter(a->a.getEstado()==EstadoActa.GENERADA).count(),am.stream().filter(a->a.getEstado()==EstadoActa.FIRMADA).count(),mensual,total);}
 long cnt(List<Contrato> c,EstadoContrato e){return c.stream().filter(x->x.getEstadoContrato()==e).count();}
 public Map<String,Long> porEstado(){return contratos.findAll().stream().peek(Contrato::recalcular).collect(Collectors.groupingBy(c->c.getEstadoContrato()==null?"SIN_ESTADO":c.getEstadoContrato().name(),Collectors.counting()));}
 public Map<String,Long> porProveedor(){return contratos.findAll().stream().collect(Collectors.groupingBy(c->c.getProveedor()==null?"SIN PROVEEDOR":c.getProveedor().getRazonSocial(),Collectors.counting()));}
 public List<Contrato> proximos(){return contratos.findByFechaFinBetween(LocalDate.now(),LocalDate.now().plusDays(90));}
}
