package com.bn.atmcontratos.service;
import com.bn.atmcontratos.model.entity.*; import com.bn.atmcontratos.model.enums.*; import com.bn.atmcontratos.repository.*; import com.bn.atmcontratos.util.*; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.core.io.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile; import java.nio.file.*; import java.util.*;
@Service @RequiredArgsConstructor public class DocumentoService{
 private final DocumentoRepository repo; private final ContratoRepository contratos; private final AtmRepository atms; private final ProveedorRepository proveedores; private final ActaConformidadRepository actas; @Value("${app.upload-dir:uploads}") String upload;
 public List<Documento> list(){return repo.findAll();} public Documento get(Long id){return repo.findById(id).orElseThrow(()->new RuntimeException("Documento no encontrado"));}
 public Documento upload(MultipartFile f,TipoDocumento t,Long contratoId,Long atmId,Long proveedorId,String desc)throws Exception{String folder=t==TipoDocumento.ACTA_FIRMADA?"actas-firmadas":(t==TipoDocumento.CONTRATO||t==TipoDocumento.ADENDA?"contratos":"otros");Path dir=Path.of(upload,folder);Files.createDirectories(dir);String name=FileUtil.ts(f.getOriginalFilename());Path path=dir.resolve(name);f.transferTo(path);Documento d=Documento.builder().tipoDocumento(t).nombreArchivo(name).rutaArchivo(path.toString()).extension(FileUtil.ext(name)).tamanio(Files.size(path)).descripcion(desc).usuarioSubida("usuario").build(); if(contratoId!=null)d.setContrato(contratos.findById(contratoId).orElseThrow()); if(atmId!=null)d.setAtm(atms.findById(atmId).orElseThrow()); if(proveedorId!=null)d.setProveedor(proveedores.findById(proveedorId).orElseThrow()); return repo.save(d);}
 public Resource download(Long id)throws Exception{return new UrlResource(Path.of(get(id).getRutaArchivo()).toUri());}
 @Transactional public void delete(Long id)throws Exception{Documento d=get(id);try{Files.deleteIfExists(Path.of(d.getRutaArchivo()));}catch(Exception ignored){} if(d.getActa()!=null){ActaConformidad a=d.getActa();boolean eraFirmada=Objects.equals(safe(a.getRutaArchivoFirmado()),safe(d.getRutaArchivo())) || d.getTipoDocumento()==TipoDocumento.ACTA_FIRMADA; if(eraFirmada){a.setNombreArchivoFirmado(null);a.setRutaArchivoFirmado(null);a.setFechaSubidaFirmada(null);a.setEstado(EstadoActa.GENERADA);actas.save(a);}} repo.delete(d);}
 private String safe(String v){return v==null?"":v;}
}
